-- setup_users.sql
-- DEPRECATED: This file is superseded by database/schema.sql which is the canonical migration.
-- Do NOT run this file. It is kept for reference only.
--
-- The users table is now defined in schema.sql with:
--   password VARCHAR(255)   (bcrypt-compatible length)
--   updated_at column
--   UNIQUE constraint on email
--
-- To create the admin user, run schema.sql first, then set a bcrypt password:
--   Step 1: Generate hash
--     node -e "import('bcrypt').then(b => b.default.hash('yourpassword', 10).then(console.log))"
--   Step 2: Insert admin
--     INSERT INTO users (username, password, role) VALUES ('admin', '<paste_hash_here>', 'admin');
--     OR update existing:
--     UPDATE users SET password = '<paste_hash_here>' WHERE username = 'admin';
